language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
os:
  - linux
  - osx
  - windows
before_script:
  - cargo build --release --verbose
before_deploy:
  - mv target/release/aaai21 "target/release/aaai21-$TRAVIS_TAG-$TRAVIS_OS_NAME"
deploy:
  - provider: releases
    skip_cleanup: true
    draft: true
    "on":
      condition: "$TRAVIS_RUST_VERSION = stable"
      branch: master
    file_glob: true
    file:
      - target/release/aaai21-*
    api_key:
      secure: "SL8j5+idA+JQ6BqRl6syDz0RuvqaBb7SPy79aGAbDRvAnJ2rGMVhg+8srBu2faFa/a5uFufh8bzGI3NrIeT+MnTfqu6vRtgNIpgCb2ia9DR/RxeJ0L53ZcygPnSb9L1SsEKTqwNcDl3fBN0CMZIGtNdZ0tL/8gi5SY2W0k3vIGtQjdeYsc9b2TTpJCr8f25zHxmBOJ6NUtL/fq4qyTHaHjvjWlYHlaDBjMSYHUWAtb4mT20cT7h3pLY4w5N8MpBtYBxv8hugamfmlWce5g/jKrN+N/aDyBDr2iX32my/MGrlEHOLCHCOKdc77NIduoi5BFbFYTU8/R4oaoU+vsX7NFg8zr5OWyXxuj8Na0VZKdl+hTBnNCPjsXKkxSCube624Ace/HSZRGRv9ZLbJJLSC8irKCVjDpQpY76MfEISct+mbOzByxru25DPm0yD9TGNog5iwVDRrwiT0pLPexsjU7K94eM+nvDuSBckukrrHYlpqgdmHEUxsHSsuFnrv1UjKRp7VeZ4MwmaaYj4SvRohSeHZ0FDzy1/OtaZwsxO6Znma283UBzclRwBfr8RqSFUTO6Y9aQD9AXbn9Kk4WoUHnhSRn348BNNujo2YoYtBAQc3zQr79yZxPamo9NSyt+1EpULJlvEO+D42xdr86ZzxDN5+S6U5E3UqZeyZuMu348="
